<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<OutputType>WinExe</OutputType>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<AssemblyName>FluentCanvas</AssemblyName>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>Resources\FluentCanvas.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
		<Platforms>x86;x64;ARM64</Platforms>
		<PlatformTarget Condition="'$(Platform)' == 'x86'">x86</PlatformTarget>
		<PlatformTarget Condition="'$(Platform)' == 'x64'">x64</PlatformTarget>
		<PlatformTarget Condition="'$(Platform)' == 'ARM64'">ARM64</PlatformTarget>
		<PlatformTarget Condition="'$(PlatformTarget)' == '' and '$(RuntimeIdentifier)' == 'win-x86'">x86</PlatformTarget>
		<PlatformTarget Condition="'$(PlatformTarget)' == '' and '$(RuntimeIdentifier)' == 'win-x64'">x64</PlatformTarget>
		<PlatformTarget Condition="'$(PlatformTarget)' == '' and '$(RuntimeIdentifier)' == 'win-arm64'">ARM64</PlatformTarget>
		<RuntimeIdentifier Condition="'$(Platform)' == 'x86'">win-x86</RuntimeIdentifier>
		<RuntimeIdentifier Condition="'$(Platform)' == 'x64'">win-x64</RuntimeIdentifier>
		<RuntimeIdentifier Condition="'$(Platform)' == 'ARM64'">win-arm64</RuntimeIdentifier>
		<PublishTrimmed>false</PublishTrimmed>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\FluentCanvas.InkAnalyzerCore\FluentCanvas.InkAnalyzerCore.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260804001" />
		<PackageReference Include="Microsoft.Office.Interop.PowerPoint">
			<Version>15.0.4420.1018</Version>
			<EmbedInteropTypes>true</EmbedInteropTypes>
		</PackageReference>
		<PackageReference Include="MicrosoftOfficeCore16">
			<Version>16.0.16626.20000</Version>
			<EmbedInteropTypes>true</EmbedInteropTypes>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json">
			<Version>13.0.3</Version>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<WCFMetadata Include="Connected Services\" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Resources\DeveloperAvatars\ChangSakura.png" />
		<Resource Include="Resources\DeveloperAvatars\clover-yan.png" />
		<Resource Include="Resources\DeveloperAvatars\CN-Ironegg.jpg" />
		<Resource Include="Resources\DeveloperAvatars\jiajiaxd.jpg" />
		<Resource Include="Resources\DeveloperAvatars\kengwang.png" />
		<Resource Include="Resources\DeveloperAvatars\Raspberry-Monster.jpg" />
		<Resource Include="Resources\DeveloperAvatars\STBBRD.png" />
		<Resource Include="Resources\DeveloperAvatars\WXRIW.png" />
		
		<Resource Include="Resources\FluentCanvas.ico" />
		<Resource Include="Resources\Segoe Fluent Icons.ttf" />
		<Resource Include="Resources\Icons-png\check-box-background.png" />
		<Resource Include="Resources\Icons-png\checked-black.png" />
		<Resource Include="Resources\Icons-png\checked-white.png" />
		<Resource Include="Resources\Icons-png\Desmos.png" />
		<Resource Include="Resources\Icons-png\EasiCamera.png" />
		<Resource Include="Resources\Icons-png\penUpright.png" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Resources\DeveloperAvatars\*.*;Resources\Icons-png\*.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Resource Update="Resources\**\*">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Resource>
	  <Compile Remove="Properties\Settings.Designer.cs" />
	  <None Update="Properties\Settings.settings">
	    <Generator></Generator>
	  </None>
	</ItemGroup>
</Project>
